### ISSUE TITLE
Performance comparison to C version

### ISSUE THREAD

**Issue by repi** [bodil/meowhash-rs#1]
Awesome that you ported this to a native Rust crate, thanks! 

Did some quick manual performance comparison with the C version (though take these with a big grain of salt as may not be fully accurate) and currently it was running at 1.73x the time of the C version for me. 

Assuming my tests were correct, any ideas or thoughts on what could be the source of perf diffs between the Rust and C (SSE AES-NI) implementation?

This was on a MBP13 @ 3.5 GHz hashing a 1 MB chunk in the benchmarking modes with Rust 1.29.1 nightly:

```
MeowHash SSE AES-NI (C):    63 859 ns  (15292 MB/s, 4.474077 bytes/cycle)
meowhash-rs (Rust):        112 992 ns  (8850 MB/s)
twox-hash xx64 (Rust):      76 061 ns  (13785 MB/s)
```

Would be great if anyone else wants to do some benchmark comparisons and share as well, esp. interested of Windows desktop results.

Oh and thanks again for creating this crate!

**Comment by bitshifter** [comment]
I looked at the output from `cargo asm` and calls to `core::coresimd::x86::aes::_mm_aesdec_si128` were not getting inlined, which is odd and could explain poor performance. For example https://rust.godbolt.org/z/-_OvBe. This is probably a Rust bug, other instrinsics are inlined (e.g. replace `_mm_aesdec_si128` with `_mm_and_si128` in the godbolt example.

**Comment by lachlansneff** [comment]
It's probably best to take a look at the generated assembly, but I have a hunch llvm isn't optimizing out bounds checking.

**Comment by nicokoch** [comment]
The SIMD functions in this crate are not annotated with `#[target_feature(enable = "sse2")]`. Maybe this has an effect on inlining?

**Comment by repi** [comment]
Adding `#[target_feature(enable="aes")]` to the unsafe functions fixes the performance and allows them to be inlined. 

`test digest_3_1m` went from 110,758 ns to 38,966 ns (8850 -> 26069 MB/s) on my MBP13 , very nice!

Thanks to Cameron Hart who suggested I try it out.

I'll file a PR once GitHub starts acting up.

**Comment by phjeltman** [comment]
> I looked at the output from `cargo asm` and calls to `core::coresimd::x86::aes::_mm_aesdec_si128` were not getting inlined, which is odd and could explain poor performance. For example https://rust.godbolt.org/z/-_OvBe. This is probably a Rust bug, other instrinsics are inlined (e.g. replace `_mm_aesdec_si128` with `_mm_and_si128` in the godbolt example.

If I add #[target_feature(enable = "aes")], the inlining works properly:
https://rust.godbolt.org/z/aMv8WZ
