### ISSUE TITLE
Increase visibility of this project upstream as an unofficial port

### ISSUE THREAD

**Issue by ErichDonGubler** [bodil/meowhash-rs#13]
Upstream Meowhash is actually now putting [alternative implementations on display](https://github.com/cmuratori/meow_hash#unofficial-ports) -- this might be a good opportunity to attract contributors, if you're interested! :)

**Comment by yerke** [comment]
I took liberty to make a PR: https://github.com/cmuratori/meow_hash/pull/77
I hope nobody minds...

**Comment by yerke** [comment]
PR was merged. I think this issue can be closed now.

**Comment by ErichDonGubler** [comment]
@yerke: Sure, I can close this issue. I'm worried about the lack of consensus from @bodil, but I guess that's orthogonal to the status of this suggestion being implemented at this point.
