### ISSUE TITLE
Is the arm code actually correct?

### ISSUE THREAD

**Issue by mmozeiko** [bodil/meowhash-rs#15]
I don't know rust, but [vaesdq_u8](https://github.com/bodil/meowhash-rs/blob/master/src/arm.rs#L42) operation works very differently from [_mm_aesdec_si128](https://github.com/bodil/meowhash-rs/blob/master/src/x86.rs#L42)

On x86 aesdec operation performs InvShiftRows, InvSubBytes, InvMixColumns and xor with key - full AES round.
On ARM vaesdq operation performs only xor with key, InvShiftRows and InvSubBytes (in that order) - only partial AES round.

So a very different operation. I'd say targeting ARM with this code will give you very broken Meow hash.

For reference, here's my ARMv8 neon code that gives exactly same result as original x86 code: https://gist.github.com/mmozeiko/f9c999dda7dbb03722409854a1c39cc2

**Comment by bodil** [comment]
There's no ARM support in the latest published version, so no, it won't give you correct results on ARM, it will give you a compile error.
