### ISSUE TITLE
Implement std::hash::Hasher trait

### ISSUE THREAD

**Issue by maciejhirsz** [bodil/meowhash-rs#3]
I wanted to add meowhash to https://github.com/maciejhirsz/lhc, but the trait isn't implemented. This is super useful you want to allow your hasher to be used with HashMaps and such.

**Comment by bodil** [comment]
That's deliberate - meowhash is intended for hashing very large data sets, and any reasonable usage of `HashMap` tends to have key sizes that rarely even fill meowhash's buffer once, making it a severe underperformer compared to Rust's default hasher. It deliberately implements [`Digest`](https://docs.rs/digest/0.8.0/digest/trait.Digest.html) instead for this reason.

**Comment by maciejhirsz** [comment]
Right! That makes sense. Someone suggested using it for small keys to me, so you can imagine my puzzlement. Thanks for clarifying!
