### ISSUE TITLE
Build fails on the i386 architecture

### ISSUE THREAD

**Issue by yurivict** [bodil/meowhash-rs#5]
```
error[E0432]: unresolved import `core::arch::x86_64`
  --> /wrkdirs/usr/ports/graphics/rx/work/rx-0.3.2/cargo-crates/meowhash-0.1.2/src/lib.rs:30:17
   |
30 | use core::arch::x86_64::*;
   |                 ^^^^^^ could not find `x86_64` in `arch`

```

See the log here: http://beefy5.nyi.freebsd.org/data/120i386-default/523997/logs/rx-editor-0.3.2.log

**Comment by bodil** [comment]
x86_64 is the only arch supported currently, but I strongly suspect adding i386 would be as easy as changing the name of the import to match the target arch. I'll look into it.

**Comment by bodil** [comment]
It was.  😊
