### ISSUE TITLE
Does not build on ARM64

### ISSUE THREAD

**Issue by icefoxen** [bodil/meowhash-rs#7]
Pretty much what it says on the tin: it tries to use `core::arch::x86_64::*` without a feature guard, and so doesn't build on non-x86_64 platforms.  If you want I can attempt to make a non-SIMD version of whatever code uses it so there's a fallback that works on any platform.

**Comment by bodil** [comment]
Are you sure you're using the latest version (0.1.3)? Because it was supposed to add aarch64 support.

**Comment by icefoxen** [comment]
Aha, I was trying to build a program that was using 0.1.2 ... then when I switched to building it myself I wasn't building with nightly.  Brain fart; thanks!

**Comment by bodil** [comment]
I'm about to break aarch64 again, though, I've ported the v0.5 upstream implementation, which breaks ARM compatibility in all kinds of ways. But 0.1.3 as published should of course continue to work.
